//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSoft.Web.SA.Tree {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtTreeText;
		protected global::System.Web.UI.WebControls.TextBox txtParentID;
		protected global::System.Web.UI.WebControls.TextBox txtParentPath;
		protected global::System.Web.UI.WebControls.TextBox txtLocation;
		protected global::System.Web.UI.WebControls.TextBox txtOrderID;
		protected global::System.Web.UI.WebControls.TextBox txtComment;
		protected global::System.Web.UI.WebControls.TextBox txtUrl;
		protected global::System.Web.UI.WebControls.TextBox txtPermissionID;
		protected global::System.Web.UI.WebControls.TextBox txtImageUrl;
		protected global::System.Web.UI.WebControls.TextBox txtModuleID;
		protected global::System.Web.UI.WebControls.TextBox txtKeShiDM;
		protected global::System.Web.UI.WebControls.TextBox txtKeshiPublic;
		protected global::System.Web.UI.WebControls.TextBox txtTreeType;
		protected global::System.Web.UI.WebControls.CheckBox chkEnabled;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
