//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSoft.Web.SA.Tree {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblNodeID;
	protected global::System.Web.UI.WebControls.Label lblTreeText;
	protected global::System.Web.UI.WebControls.Label lblParentID;
	protected global::System.Web.UI.WebControls.Label lblParentPath;
	protected global::System.Web.UI.WebControls.Label lblLocation;
	protected global::System.Web.UI.WebControls.Label lblOrderID;
	protected global::System.Web.UI.WebControls.Label lblComment;
	protected global::System.Web.UI.WebControls.Label lblUrl;
	protected global::System.Web.UI.WebControls.Label lblPermissionID;
	protected global::System.Web.UI.WebControls.Label lblImageUrl;
	protected global::System.Web.UI.WebControls.Label lblModuleID;
	protected global::System.Web.UI.WebControls.Label lblKeShiDM;
	protected global::System.Web.UI.WebControls.Label lblKeshiPublic;
	protected global::System.Web.UI.WebControls.Label lblTreeType;
	protected global::System.Web.UI.WebControls.Label lblEnabled;


       
    }
}
